---
- name: Restart nginx-nr-agent
  service:
    name: nginx-nr-agent
    state: restarted
    enabled: yes

- name: Start nginx-nr-agent
  service:
    name: nginx-nr-agent
    state: started
    enabled: yes

- name: Stop nginx-nr-agent
  service:
    name: nginx-nr-agent
    state: stopped
    enabled: yes
